<a href="https://colab.research.google.com/github/krishnavenib5/AIML-IIITH-Code/blob/U1-M1H1/Copy_of_U1_MH1_Data_Munging_Kris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Learning Objective

At the end of this experiment, you will be able to:

* perform Data preprocessing

In [ ]:
#@title  Mini Hackathon Walkthrough
from IPython.display import HTML

HTML("""<video width="640" height="420" controls>
  <source src="https://cdn.talentsprint.com/talentsprint/archives/sc/aiml/aiml_batch_15/preview_videos/Mini_Hackathon_Data_Munging_Briefing.mp4" type="video/mp4">
</video>
""")

## Problem Statement

We will be using district wise demographics, enrollments, and teacher indicator data to predict whether the literacy rate is high/ medium/ low in each district.

### Data Preprocessing

Data preprocessing is an important step in solving every machine learning problem. Most of
the datasets used with Machine Learning problems need to be processed / cleaned / transformed
so that a Machine Learning algorithm can be trained on it.

There are different steps involved in Data Preprocessing. These steps are as follows:

    1. Data Cleaning → In this step the primary focus is on
        - Handling missing data
        - Handling noisy data
        - Detection and removal of outliers
    
    2. Data Integration → This process is used when data is gathered from various data sources and data are combined to form consistent data.
    This data after performing cleaning is used for analysis.
    
    3. Data Transformation → In this step we will convert the raw data into a specified format according to the need of the model we are building.
    There are many options used for transforming the data as below:
        - Normalization
        - Aggregation
        - Generalization
        
    4. Data Reduction → Following data transformation and scaling, the redundancy within the data is removed and is organized efficiently.

### Total Marks  = 20

In [3]:
# @title Download the datasets
from IPython import get_ipython

ipython = get_ipython()

notebook="U1_MH1_Data_Munging" #name of the notebook

def setup():
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/B15_Data_Munging.zip")
    ipython.magic("sx unzip B15_Data_Munging.zip")
    print("Data downloaded successfully")
    return

setup()

Data downloaded successfully

In [2]:
!ls

sample_data

## Exercise 1 - Load and Explore the Data (3 Marks)
1. We have three different files

  * Districtwise_Basicdata.csv
  * Districtwise_Enrollment_details_indicator.csv
  * Districtwise_Teacher_indicator.csv

  These files contain the necessary data to solve the problem. <br>

2. Load the files based on **team allocation** mentioned below. Observe the header level details, data records while loading the data.
  
  Hint : Use read_csv from pandas with [skiprows or header](https://towardsdatascience.com/import-csv-files-as-pandas-dataframe-with-skiprows-skipfooter-usecols-index-col-and-header-fbf67a2f92a) options.

3. Read the columns of the dataset and rename them if required.

  Hint : Rename column names (if any) using the following [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html).

Team allocation for dataset selection

    Team A = 1,3,5,7,9,11,13,15
        Districtwise_Basicdata.csv
        Districtwise_Enrollment_details_indicator.csv

    Team B = 2,4,6,8,10,12,14
        Districtwise_Basicdata.csv
        Districtwise_Teacher_indicator.csv

In [20]:
# Importing all the required packages and add necessary imports if required
import pandas as pd
import numpy as np

In [28]:
# YOUR CODE HERE for loading and exploring the datasets
# 1. Load df_basic (headers are already clean on row 0)
df_basic = pd.read_csv('Districtwise_Basicdata.csv')

# 2. Load df_enrollment using row 1 as the column header
# This automatically skips row 0 (the metadata row containing "District Code", etc.)
df_enrollment = pd.read_csv('Districtwise_Enrollment_details_indicator.csv',header=1)

# Correct column names and data rows for df_enrollment and df_basic ---
# Also, the first two rows (index 0 and 1) of df_enrollment are metadata/alternative headers.
df_enrollment.rename(columns={'Unnamed: 0': 'Year', 'Unnamed: 1': 'State Code', 'Unnamed: 2': 'State Name'}, inplace=True)
df_enrollment = df_enrollment.iloc[2:].reset_index(drop=True) #It slices off the top metadata rows and resets the index back to zero.

# Correct df_basic as it also has a metadata row at index 0 after initial load
df_basic = df_basic.iloc[1:].reset_index(drop=True)

# 3. Explore and verify the column headers
print("--- Basic Data Columns ---")
print(list(df_basic.columns[:]))  # Shows the first 5 columns

print("\n--- Enrollment Data Columns ---")
print(list(df_enrollment.columns[:5]))  # Shows the first 5 columns

# 4. Optional Exploration
print(f"\nBasic Data Shape: {df_basic.shape}")
print(f"Enrollment Data Shape: {df_enrollment.shape}")

df_basic.head()
#df_enrollment.head()

--- Basic Data Columns ---
['Year', 'State Code', 'State Name', 'District Code', 'District Name', 'Number of Blocks', 'Number of Clusters', 'Number of Villages', 'Total Number of Schools', 'Total Poulation', '0-6 Population', 'Percentage Urban Population', 'Sexratio', 'Sex Ratio 0-6', 'Decadal Growth Rate', 'Percentage SC Population', 'Percentage ST Population', 'Overall Literacy', 'Female Literacy']

--- Enrollment Data Columns ---
['Year', 'State Code', 'State Name', 'District Code', 'District Name']

Basic Data Shape: (1324, 19)
Enrollment Data Shape: (1324, 166)

,Year,State Code,State Name,District Code,District Name,Number of Blocks,Number of Clusters,Number of Villages,Total Number of Schools,Total Poulation,0-6 Population,Percentage Urban Population,Sexratio,Sex Ratio 0-6,Decadal Growth Rate,Percentage SC Population,Percentage ST Population,Overall Literacy,Female Literacy
0,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,3,16,83,212,237586,23616.05,55.89,874,980,13.97,0,1.72,High,84.52
1,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,3,13,76,181,105539,11651.51,2.6,925,975,-0.07,0,0.72,High,79.39
2,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3502,NICOBARS ...,3,8,42,58,36819,4226.82,0,778,961,-12.48,0,64.28,High,70.7
3,2012-13,28,ANDHRA PRADESH ...,2801,ADILABAD ...,52,356,1576,4983,2737738,295675.7,27.68,1003,942,10.04,17.82,18.09,Low,51.99
4,2012-13,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,63,564,929,5188,4083315,427114.75,28.09,977,927,12.16,14.29,3.78,Low,54.31

## Exercise 2  - Data Integration (3 Marks)

As the required data is present in different datasets, we need to **integrate both to make a single dataframe/dataset**.
  * For integrating the datasets, create a unique identifier for each row in both the dataframes so that it can be used to map the data in different files.
   
    * Combine year, state code, district code columns and form a new unique identifier column, refer to this [link](https://stackoverflow.com/questions/33098383/merge-multiple-column-values-into-one-column-in-python-pandas).
    * Set the identifier column as the index for each dataframe.

    * Integrate the dataframes using the above index
     
     Hint: For merging or joining the datasets, refer to this [link](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html)

**Example:** Data of the district Anantapur in Andrapradesh, which is present in different files should form a single row after integrating the datasets

In [24]:
# --- Step 1: Ensure columns are strings and stripped of whitespace ---
df_basic['Year'] = df_basic['Year'].astype(str).str.strip()
df_basic['State Code'] = df_basic['State Code'].astype(str).str.strip()
df_basic['District Code'] = df_basic['District Code'].astype(str).str.strip()

# For df_enrollment (now with correct column names and data rows)
df_enrollment['Year'] = df_enrollment['Year'].astype(str).str.strip()
df_enrollment['State Code'] = df_enrollment['State Code'].astype(str).str.strip()
df_enrollment['District Code'] = df_enrollment['District Code'].astype(str).str.strip()


# --- Step 2: Combine columns to form the unique identifier column ---
df_basic['uid'] = df_basic['Year'] + "_" + df_basic['State Code'] + "_" + df_basic['District Code']
df_enrollment['uid'] = df_enrollment['Year'] + "_" + df_enrollment['State Code'] + "_" + df_enrollment['District Code']

# --- Step 3: Set the identifier column as the index for each dataframe ---
df_basic.set_index('uid', inplace=True)
df_enrollment.set_index('uid', inplace=True)

# --- Step 4: Integrate the dataframes using the index ---
# We use an inner join to keep only rows present across both datasets.
# lsuffix and rsuffix avoid errors by distinguishing overlapping non-key columns (like State Name)
df_integrated = df_basic.join(df_enrollment, how='inner', lsuffix='_basic', rsuffix='_enroll')


# --- Step 5: Verify the integrated result ---
print("Integrated DataFrame Shape:", df_integrated.shape)
print("\nFirst 2 rows of the integrated data:")
df_integrated.head(2)

Integrated DataFrame Shape: (1324, 185)

First 2 rows of the integrated data:

,Year_basic,State Code_basic,State Name_basic,District Code_basic,District Name_basic,Number of Blocks,Number of Clusters,Number of Villages,Total Number of Schools,Total Poulation,...,Unnamed: 156,Unnamed: 157,Muslim Enrolment,Unnamed: 159,Unnamed: 160,Unnamed: 161,OBC Enrolment,Unnamed: 163,Unnamed: 164,Unnamed: 165
uid,,,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,3,16,83,212,237586,...,7,4,2539,1383,1263,690,2289,1437,1159,747
2012-13_35_3503,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,3,13,76,181,105539,...,0,0,184,103,98,60,2100,1621,1066,825

## Exercise 3 - Data Cleaning (3 Marks)

1.  **Overall_lit** is our target variable. Delete rows with missing overall_lit value

   Hint: Refer to the link [dropna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html).


2.  Convert categorical values to numerical values.

  For example, If a feature contains categorical values such as dog, cat, mouse, etc then replace them with 0, 1, 2, etc or use [Sklearn LabelEncoder's](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)

3. Replace the missing values in any other column appropriately with mean / median / mode.

  Hint: Use pandas [fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) function to replace the missing values

In [32]:
# YOUR CODE HERE for data cleaning
from sklearn.preprocessing import LabelEncoder

# Copy the integrated dataframe to maintain a clean workflow
df_cleaned = df_integrated.copy()
print(df_cleaned.columns)
# --- Step 1: Drop rows with missing values in the target variable 'Overall Literacy' ---
# Using the exact column name from your df_basic dataset
target_col = 'Overall Literacy'

df_cleaned.dropna(subset=[target_col], inplace=True)


# --- Step 2: Convert categorical values to numerical values ---
# Identify all columns that contain string/object data types (like 'High', 'Low', 'Medium')
categorical_cols = df_cleaned.select_dtypes(include=['object']).columns

label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    # Convert column to string first to safely handle any mixed types, then encode
    df_cleaned[col] = le.fit_transform(df_cleaned[col].astype(str))
    label_encoders[col] = le  # Saved in case you need to decode values later


# --- Step 3: Replace missing values in any other column with the median ---
# Force columns to numeric where possible (leaves non-convertible columns alone)
df_cleaned = df_cleaned.apply(pd.to_numeric, errors='ignore')

# Identify numerical columns to apply median imputation safely
numeric_cols = df_cleaned.select_dtypes(include=[np.number]).columns

for col in numeric_cols:
    if df_cleaned[col].isna().sum() > 0:
        # Fill missing numeric values with the column's median value
        df_cleaned[col] = df_cleaned[col].fillna(df_cleaned[col].median())


# --- Step 4: Verify Cleaning Progress ---
print("Shape after data cleaning:", df_cleaned.shape)
print(f"Remaining missing values in '{target_col}':", df_cleaned[target_col].isna().sum())

Index(['Year_basic', 'State Code_basic', 'State Name_basic',
       'District Code_basic', 'District Name_basic', 'Number of Blocks',
       'Number of Clusters', 'Number of Villages', 'Total Number of Schools',
       'Total Poulation',
       ...
       'Unnamed: 156', 'Unnamed: 157', 'Muslim Enrolment', 'Unnamed: 159',
       'Unnamed: 160', 'Unnamed: 161', 'OBC Enrolment', 'Unnamed: 163',
       'Unnamed: 164', 'Unnamed: 165'],
      dtype='object', length=185)
Shape after data cleaning: (1268, 185)
Remaining missing values in 'Overall Literacy': 0

/tmp/ipykernel_20744/2498664681.py:28: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_cleaned = df_cleaned.apply(pd.to_numeric, errors='ignore')

## Exercise 4 - (3 Marks)

1. Remove the unnecessary columns which are not contributing to the overall literacy rate

2. Verify if there are any duplicate columns and remove them.

  For example: state name and district name are the same as state code and district code.

3. Make sure that the final dataframe has no null or nan values. Delete the rows with missing values.

   Hint: Give df.isna() to verify on the nan values in the dataframe.

In [33]:
# YOUR CODE HERE for cleaning the dataframe
# Copy the cleaned dataframe to continue the pipeline
df_final = df_cleaned.copy()

# --- Step 1 & 2: Drop redundant and duplicate structural columns ---
# State Name and District Name carry the same layout information as State Code and District Code.
# Additionally, we remove the trailing duplicate suffix columns created during the join.
columns_to_drop = [
    'Year_basic', 'Year_enroll',
    'State Name_basic', 'State Name_enroll',
    'District Name_basic', 'District Name_enroll',
    'State Code_enroll', 'District Code_enroll'
]

# Drop only the columns that exist in our current DataFrame to prevent KeyErrors
columns_to_drop = [col for col in columns_to_drop if col in df_final.columns]
df_final.drop(columns=columns_to_drop, inplace=True)


# --- Step 3: Remove remaining rows with any Null or NaN values ---
# Drop any rows containing missing records in the remaining feature columns
df_final.dropna(inplace=True)


# --- Step 4: Verify that the final dataframe has zero null values ---
print("Final DataFrame Shape after removing duplicates and NaNs:", df_final.shape)
print("\nSum of missing values across the entire DataFrame:")
print(df_final.isna().sum().sum())  # Should output exactly 0

Final DataFrame Shape after removing duplicates and NaNs: (1268, 177)

Sum of missing values across the entire DataFrame:
0

## Exercise 5 - Apply Correlation Matrix (2 Marks)

Correlation is a statistical technique that can show whether and how strongly pairs of variables are related. More number of features does not imply better accuracy. More features may lead to a decline in the accuracy and create noise in the model, if they contain any irrelevant features.

*Features with high correlation value will imply the same meaning. Hence removing the highly correlated features*

**Function Description:**

`remove_Highly_Correlated()` function removes highly correlated features in the dataframe.
- Creates a correlation matrix of row and column wise features
- Extracts only uppertriangular matrix as correlation matrix, which will have the same values below and above the diagonal
- Removes columns which are having correlation value more than the threshold value.

In [34]:
def remove_Highly_Correlated(df, bar=0.9):
  # Creates correlation matrix
  corr = df.corr()

  # Set Up Mask To Hide Upper Triangle
  mask = np.triu(np.ones_like(corr, dtype=bool))
  tri_df = corr.mask(mask)

  # Finding features with correlation value more than specified threshold value (bar=0.9)
  highly_cor_col = [col for col in tri_df.columns if any(tri_df[col] > bar )]
  print("length of highly correlated columns",len(highly_cor_col))

  # Drop the highly correlated columns
  reduced_df = df.drop(highly_cor_col, axis = 1)
  print("shape of data",df.shape,"shape of reduced data",reduced_df.shape)
  return reduced_df

In [35]:
# YOUR CODE HERE to remove highly correlated features from the dataframe by calling above function.
# --- Step 1: Separate the feature matrix (X) from the target label (y) ---
# We keep 'Overall Literacy' separate so it doesn't get evaluated or dropped
y = df_final['Overall Literacy']
X = df_final.drop(columns=['Overall Literacy'])

# --- Step 2: Call the function to remove highly correlated features ---
# This will evaluate numerical trends and drop columns with a correlation > 0.9
X_reduced = remove_Highly_Correlated(X, bar=0.9)

# --- Step 3: Verify the remaining feature space ---
print("\nRemaining feature columns count:", X_reduced.shape[1])
print("First 10 clean features:", list(X_reduced.columns[:10]))

length of highly correlated columns 10
shape of data (1268, 176) shape of reduced data (1268, 166)

Remaining feature columns count: 166
First 10 clean features: ['District Code_basic', 'Number of Blocks', 'Number of Clusters', 'Number of Villages', 'Total Number of Schools', 'Total Poulation', '0-6 Population', 'Percentage Urban Population', 'Sexratio', 'Sex Ratio 0-6']

## Exercise 6 - (3 Marks)

Perform Standard Scaling on the data feature/column wise.

**Hint:** In order to understand the idea behind the terms used above, you may refer to the following link:

[StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [36]:
# YOUR CODE HERE
from sklearn.preprocessing import StandardScaler

# --- Step 1: Initialize the StandardScaler ---
scaler = StandardScaler()

# --- Step 2: Fit and transform the reduced features ---
# This calculates the mean and standard deviation for each column and scales the data
X_scaled_array = scaler.fit_transform(X_reduced)

# --- Step 3: Convert the scaled array back to a clean DataFrame ---
# We keep the original column names and unique identifier index intact
X_scaled = pd.DataFrame(X_scaled_array, columns=X_reduced.columns, index=X_reduced.index)

# --- Step 4: Verify the transformation ---
print("Scaled DataFrame Shape:", X_scaled.shape)
print("\nVerification (First 5 feature means ~0 and standard deviations ~1):")
for col in X_scaled.columns[:5]:
    print(f"{col:<25} | Mean: {X_scaled[col].mean():.4f} | Std: {X_scaled[col].std():.4f}")

Scaled DataFrame Shape: (1268, 166)

Verification (First 5 feature means ~0 and standard deviations ~1):
District Code_basic       | Mean: -0.0000 | Std: 1.0004
Number of Blocks          | Mean: -0.0000 | Std: 1.0004
Number of Clusters        | Mean: -0.0000 | Std: 1.0004
Number of Villages        | Mean: -0.0000 | Std: 1.0004
Total Number of Schools   | Mean: -0.0000 | Std: 1.0004

## Exercise 7 - (3 Marks)

Apply different classifiers on the preprocessed data and figure out which classifier gives the best result.

* Split the data into train and test

* Fit the model with train data and find the accuracy of test data

### Expected Accuracy is above 90%

In [39]:
# YOUR CODE HERE for applying different classifiers
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# --- Step 1: Split the Data into Train and Test Sets ---
# Using 80% for training and 20% for testing.
# stratify=y ensures balanced class representation across splits.
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# --- Step 2: Initialize Classifiers ---
classifiers = {
    "Random Forest": RandomForestClassifier(n_estimators=200, max_depth=12, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=150, learning_rate=0.1, random_state=42),
    "Support Vector Classifier": SVC(kernel='rbf', C=10, gamma='scale', random_state=42)
}

# --- Step 3: Fit Models and Evaluate Accuracy ---
best_accuracy = 0
best_model_name = ""
results = {}

print("--- Classifier Performance ---")
for name, clf in classifiers.items():
    # Fit the model on training data
    clf.fit(X_train, y_train)

    # Predict on testing data
    y_pred = clf.predict(X_test)

    # Calculate accuracy score
    acc = accuracy_score(y_test, y_pred)
    results[name] = acc
    print(f"{name:<27} Test Accuracy: {acc * 100:.2f}%")

    # Track the best performing model
    if acc > best_accuracy:
        best_accuracy = acc
        best_model_name = name

--- Classifier Performance ---
Random Forest               Test Accuracy: 92.13%
Gradient Boosting           Test Accuracy: 92.91%
Support Vector Classifier   Test Accuracy: 84.65%